################################################################################
################################################################################
# YOU HAVE TO BE CAREFUL TO MAKE A MODIFICATION BELOW
################################################################################
################################################################################

# Target name
# srp3c : SRP3C
# srp3s : Slim SRP
# srp4m : SRP4 (vector architecture)
TARGET=srp4m

# Target system
# default : Default system
TARGET_SYS=sim

# Compile macro definitions
# -D__srp__          		: This is necessary for newlib
# -D__ELF__          		: This is necessary for newlib
COMPILE_MACRO_DEFINES= \
					-D__srp__ \
					-D__ELF__

# System dependent macro definitions
# -DCONFIG_ARCH_BERN 		: This is necessary for DMA as we reuse BERN DMA code.
# FIXME: CONFIG_ARCH_BERN is temporarily used for Slim SRP even
# though there is no DMA module in Slim SRP. It is necessary to
# clean up the related codes.
SYSTEM_MACRO_DEFINES= \
					-DCONFIG_ARCH_BERN

# Tools to be used
SCC=$(SRPSDK_INSTALL)/bin/scc
SCC_LD=$(SRPSDK_INSTALL)/bin/scc.ld
SCC_AR=ar
MRPSIM=$(MRPSIM_PATH)/bin/mRPsim
CC=gcc
LD=gcc
STD=gnu89
EXE=a.out

# All compilation options
# -fdata-sections				: Place each data in its own section
# -fno-vectorize				: Disable the loop vectorization passes
# -fno-slp-vectorize		: Disable the superword level parallelism vectorization passes
# -fno-zero-initialized-in-bss : 
# -mllvm -isolated-vmem	: Generate code by considering separate vector SPM (SRP4 only)
# -mllvm -enable-aa-sched-mi : Enable use of AA during MI GAD construction
# -mllvm -enable-bundle-nop-compression : Enable bundle nop compression
# -mllvm -enable-bundle-compression : Enable bundle compression
# -mllvm -enable-multi-cycle-nop : Enable multiple cycle nop instruction (compression)
# -std=gnu89						: Use gnu89 style language extension
# -Werror								: Turn all warnings into errors

# Default compiler options
OPTIONS= \
					-fdata-sections \
					-fno-vectorize \
					-fno-slp-vectorize \
					-fno-zero-initialized-in-bss \
					-std=$(STD) \
					$(COMPILE_MACRO_DEFINES) \
					$(SYSTEM_MACRO_DEFINES) \
					$(COMPILE_OPTIONS)

# Options for newlib compilation
# The compilation option for newlib is grouped separately. This is also used
# by SCC_CFLAGS. In 'buildNewlib.sh' the order of compilation option should not be
# changed. If so, there might be compilation problem.
NEWLIB_COMPILE_OPTIONS= -srp-subtarget $(TARGET) $(MACRO_DEFINES)

# Options for compiler (scc)
SCC_CFLAGS= $(NEWLIB_COMPILE_OPTIONS) $(OPTIMIZE) $(OPTIONS) -g

# Options for compiling assembly files (scc)
SCC_ASFLAGS= -c $(OPTIMIZE) -srp-subtarget $(TARGET)

# Options for creating archive (ar)
SCC_ARFLAGS= r

# Essential symbols for compilation
# YOU SHOULD NOT MODIFY THIS WITHOUT DISCUSING COMPILER DEVELOPERS
COMPILER_SYM_DEF=

# Essential symbols for system
# YOU SHOULD NOT MODIFY THIS WITHOUT DISCUSING SYSTEM DEVELOPERS
# -defsym : Symbol address
# -defsym=DMAC_CONF=0xf200 				: DMA configuration
# -defsym=DMAC_EN_CH=0xf2004			: DMA channel enable
# -defsym=DMAC_INT_STAT=0xf2010		: DMA conf
# -defsym=DMAC_INT_RSTAT=0xf2014	: DMA conf
# -defsym=DMAC_INT_CL=0xf2018			: DMA conf
# -defsym=DMAC_CH_REGS=0xf2100		: DMA channel registers
SYSTEM_SYM_DEF= \
					-defsym=_SRP_USER_STACK_ADDR_=0x07000000 \
					-defsym=_SRP_INTERRUPT_STACK_ADDR_=0x08000000 \
					-defsym=__HAL_L1_BEGIN=0x0 \
					-defsym=__HAL_L1_END=0x08000000 \
					-defsym=__HAL_L1_VECTOR_BEGIN=0x0 \
					-defsym=__HAL_L1_VECTOR_END=0x08000000 \
					-defsym=SER_UART=0xA000FFD4 \
					-defsym=SER_UART_HALF_FULL=0xA000FFD4 \
					-defsym=SER_UART_DBG=0xA000FFD8 \
					-defsym=DMAC_CONF=0x32000 \
					-defsym=DMAC_EN_CH=0x32004 \
					-defsym=DMAC_INT_STAT=0x32010 \
					-defsym=DMAC_INT_RSTAT=0x32014 \
					-defsym=DMAC_INT_CL=0x32018 \
					-defsym=DMAC_CH_REGS=0x32100

# Essential symbols
SYM_DEF= \
					$(COMPILER_SYM_DEF) \
					$(SYSTEM_SYM_DEF) \
					$(USER_SYM_DEF)

# Options for system linker (scc.ld)
SCC_LDFLAGS= -T $(LINKER_SCRIPT) $(SYM_DEF) -gc-sections

# Header file path for compile
# Add the pathes of the header files if you want
# Why is it recommended to cut off all the dependencies between hal and the other files?
# Why is the smk include in hal not good?
#  There is one problem. If someone wants to use hal directly, it is inevitable to
#  use smk as well because hal uses smk's header files. This increases the code size
# YOU SHOULD NOT MODIFY THIS WITHOUT DISCUSSING COMPILER DEVELOPERS AND SYSTEM DEVELOPERS
LIBRARY_INC:= \
					-I $(SRPSDK_SRC)/library/compiler-rt \
					-I $(SRPSDK_SRC)/library/smk \
					-I $(SRPSDK_SRC)/arch/common \
					-I $(SRPSDK_SRC)/arch/$(TARGET)/etc \
					-I $(SRPSDK_SRC)/arch/$(TARGET)/hal \
					-I $(SRPSDK_SRC)/arch/$(TARGET)/system/$(TARGET_SYS)/src \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/newlib/srp-elf/include \
					-include $(SRPSDK_SRC)/arch/$(TARGET)/etc/srp_vector.h

# Essential header include path
# YOU SHOULD NOT MODIFY THIS WITHOUT DISCUSSING COMPILER DEVELOPERS
SYSTEM_INC:= \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/common \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/compiler-rt \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/etc \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/hal \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/newlib/srp-elf/include \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/smk \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/startup \
					-I $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/system \
					-include $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/etc/srp_vector.h \
					-include $(SRPSDK_INSTALL)/include/arch/$(TARGET)/system/$(TARGET_SYS)/common/legacy.h

# Essential libraries such as HAL
# YOU SHOULD NOT MODIFY THIS WITHOUT DISCUSSING COMPILER DEVELOPERS AND SYSTEM DEVELOPERS
SYSTEM_LIBS:= \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/common \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/compiler-rt \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/etc \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/hal \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/newlib \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/smk \
					-L $(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/system \
					-start-group -lcommon -lcompiler-rt -letc -lhal -lc -lm -lsrp -lsmk -lsystem -end-group

STARTUP_OBJS:= \
					$(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/startup/crt0.o \
					$(SRPSDK_INSTALL)/lib/arch/$(TARGET)/system/$(TARGET_SYS)/startup/isr.o

SCC_INC+=$(shell find . -type d | grep -v "\.svn" | grep -v -E "' '|$(SCC_EXCLUDES)" | sed -e "s/^./-I ./")
SRCS:=$(shell find . -name "*.c" | grep -v -E "' '|$(SCC_EXCLUDES)")
SRC_ASMS:=$(patsubst %c,%s,$(SRCS))
ASMS:=$(shell find . -name "*.s" | grep -v -E "' '|$(SCC_EXCLUDES)")
OBJS:=$(patsubst %c,%o,$(SRCS))
ASM_OBJS:=$(patsubst %s,%o,$(ASMS))
SCC_LIBS:=$(USER_LIBS) $(SYSTEM_LIBS)

MODE:=CROSS_COMPILE
TARGET_BIN=$(OUTPUT_DIR)/$(EXE)
LDSCRIPT_NAME=ldscript
ifeq ($(findstring -g, $(OPTIMIZE)), -g)
  LDSCRIPT_NAME:=$(LDSCRIPT_NAME).dbg
endif

%.o: %.c
ifeq ($(MODE), HOST_COMPILE)
	$(CC) -c -g -O0 -o $@ $< $(SCC_INC) $(LIBRARY_INC)
else
ifeq ($(LIBGEN), TRUE)
	$(SCC) -c $(SCC_CFLAGS) -o $@ $< $(SCC_INC) $(LIBRARY_INC)
else
	$(SCC) -c $(SCC_CFLAGS) -o $@ $< $(SCC_INC) $(SYSTEM_INC)
endif
endif

%.s : %.c
	$(SCC) -S $(SCC_CFLAGS) -o $@ $< $(SCC_INC) $(SYSTEM_INC)

%.o : %.s
	$(SCC) $(SCC_ASFLAGS) -o $@ $<

.PHONY: lib clean dis sym run help asm

print-%:
	@echo $($*)

out: $(TARGET_BIN)

$(TARGET_BIN): $(OBJS) $(ASM_OBJS)
	$(SCC_LD) -o $(OUTPUT_DIR)/$(EXE) $(SCC_LDFLAGS) $(STARTUP_OBJS) $(OBJS) $(ASM_OBJS) $(SCC_LIBS)

asm: $(SRC_ASMS)

lib: $(OBJS) $(ASM_OBJS)
	$(SCC_AR) $(SCC_ARFLAGS) lib $(OBJS) $(ASM_OBJS)

run: $(OUTPUT_DIR)/$(EXE)
	$(MRPSIM) --command cmd

dis:
	scc-objdump -disassemble -g -triple=srp-$(TARGET)-xx $(OUTPUT_DIR)/$(EXE)

sym:
	readelf -s $(OUTPUT_DIR)/$(EXE)

host: $(OBJS)
	$(LD) -o host $(OBJS)

clean::
	rm -f $(OUTPUT_DIR)/$(EXE) lib $(OBJS) $(SRC_ASMS) uart_out.mRPsim fifo_out mRPsim.vcd *.dump host *.profile

help:
	@echo
	@echo "SRP Compiler Collection"
	@echo
	@echo "make [-jn] : make binary, n: number of threads, more means faster"
	@echo "make run   : make binary and run on mRPsim"
	@echo "make dis   : disassemble"
	@echo "make sym   : show symbols"
	@echo "make clean : clean objects and binary"
	@echo "make asm   : make assembly files"
	@echo
